### PR TITLE
Fixed and uniformized the appending of colons to fs names

### PR DESCRIPTION
**Pull request by HexPandaa**

### CODE REVIEW

**Comment by HexPandaa** [comment]
This should fix the purge of folders in the Web UI.

**Comment by negative0** [comment]
@HexPandaa Thanks for doing this. Could you convert this in a single commit and push it?

**Comment by HexPandaa** [comment]
Sorry I had a hard time doing it, it was my first time but it should be good now.

**Comment by negative0** [comment]
Thanks for doing this! I will merge this now.

**Pull request merged**
